`include "primer1_command_core_part_0.svh"
`include "primer1_command_core_part_1.svh"
`include "primer1_command_core_part_2.svh"
`include "primer1_command_core_part_3.svh"
`include "primer1_command_core_part_4.svh"
`include "primer1_command_core_part_5.svh"
