// Generated by software/reference/generate_kiwi_primer20k_selftest.py.
// Do not edit this file manually.
//
// Expected canonical q=3329 output for a 256-coefficient ramp input:
//     input[i] = i, for i = 0..255.

module forward_ntt_ramp_expected_rom (
    input  logic [7:0]  addr_i,
    output logic [15:0] expected_o
);
    logic [15:0] memory [0:255];

    initial begin
        $readmemh(
            "rtl/boards/kiwi_primer_20k/forward_ntt_ramp_expected.hex",
            memory
        );
    end

    always_comb expected_o = memory[addr_i];
endmodule
