#!/usr/bin/env python3
"""Generate and verify the Kiwi Primer 20K forward-NTT self-test ROM.

The board self-test loads the deterministic ramp polynomial ``input[i] = i``,
runs the complete 256-coefficient forward NTT and compares every result against
a synthesizable expected-value ROM. The expected values are checked with both
software NTT implementations already used by the integration test.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from generate_forward_ntt_vectors import forward_ntt_direct, forward_ntt_flat
from generate_twiddles_3329 import Q, derive_standard_twiddles

N = 256
ROOT = Path(__file__).resolve().parents[2]
BOARD_DIR = ROOT / "rtl/boards/kiwi_primer_20k"
ROM_TARGET = BOARD_DIR / "forward_ntt_ramp_expected_rom.sv"
HEX_TARGET = BOARD_DIR / "forward_ntt_ramp_expected.hex"


def build_expected() -> list[int]:
    inputs = list(range(N))
    twiddles = derive_standard_twiddles()
    direct = forward_ntt_direct(inputs, twiddles)
    flattened = forward_ntt_flat(inputs, twiddles)

    if direct != flattened:
        mismatch = next(
            index
            for index, pair in enumerate(zip(direct, flattened))
            if pair[0] != pair[1]
        )
        raise AssertionError(
            f"self-test model mismatch at coefficient {mismatch}: "
            f"direct={direct[mismatch]} flat={flattened[mismatch]}"
        )

    if len(direct) != N:
        raise AssertionError(f"expected {N} outputs, got {len(direct)}")
    if any(not 0 <= value < Q for value in direct):
        raise AssertionError("self-test produced a non-canonical coefficient")

    return direct


def render_hex(values: list[int]) -> str:
    return "".join(f"{value:04x}\n" for value in values)


def render_systemverilog() -> str:
    return """// Generated by software/reference/generate_kiwi_primer20k_selftest.py.
// Do not edit this file manually.
//
// Expected canonical q=3329 output for a 256-coefficient ramp input:
//     input[i] = i, for i = 0..255.

module forward_ntt_ramp_expected_rom (
    input  logic [7:0]  addr_i,
    output logic [15:0] expected_o
);
    logic [15:0] memory [0:255];

    initial begin
        $readmemh(
            "rtl/boards/kiwi_primer_20k/forward_ntt_ramp_expected.hex",
            memory
        );
    end

    always_comb expected_o = memory[addr_i];
endmodule
"""


def write_or_check(path: Path, expected: str, check_only: bool) -> bool:
    if check_only:
        if not path.exists():
            print(f"ERROR: missing generated file: {path}", file=sys.stderr)
            return False
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            print(
                f"ERROR: stale generated file: {path}\n"
                "Run: python3 software/reference/"
                "generate_kiwi_primer20k_selftest.py --write",
                file=sys.stderr,
            )
            return False
        return True

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    print(f"WROTE: {path}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    values = build_expected()
    targets = (
        (ROM_TARGET, render_systemverilog()),
        (HEX_TARGET, render_hex(values)),
    )
    ok = all(
        write_or_check(path, expected, args.check)
        for path, expected in targets
    )
    if not ok:
        return 1

    action = "verified" if args.check else "generated"
    print(
        f"PASS: {action} Kiwi Primer 20K ramp self-test ROM; "
        f"{N} canonical coefficients, first={values[0]}, last={values[-1]}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
