#!/usr/bin/env python3
"""Generate and verify the ML-KEM q=3329 twiddle ROM.

The official CRYSTALS-Kyber reference implementation stores signed
Montgomery-domain zetas. This repository's current butterfly multiplier is a
standard modular multiplier, so this script converts those constants to
canonical standard-domain representatives before emitting RTL and test vectors.

Source constants:
https://github.com/pq-crystals/kyber/blob/main/ref/ntt.c
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

Q = 3329
ROOT_OF_UNITY = 17
MONTGOMERY_R = (1 << 16) % Q

BIT_REVERSED_TREE = (
    0, 64, 32, 96, 16, 80, 48, 112, 8, 72, 40, 104, 24, 88, 56, 120,
    4, 68, 36, 100, 20, 84, 52, 116, 12, 76, 44, 108, 28, 92, 60, 124,
    2, 66, 34, 98, 18, 82, 50, 114, 10, 74, 42, 106, 26, 90, 58, 122,
    6, 70, 38, 102, 22, 86, 54, 118, 14, 78, 46, 110, 30, 94, 62, 126,
    1, 65, 33, 97, 17, 81, 49, 113, 9, 73, 41, 105, 25, 89, 57, 121,
    5, 69, 37, 101, 21, 85, 53, 117, 13, 77, 45, 109, 29, 93, 61, 125,
    3, 67, 35, 99, 19, 83, 51, 115, 11, 75, 43, 107, 27, 91, 59, 123,
    7, 71, 39, 103, 23, 87, 55, 119, 15, 79, 47, 111, 31, 95, 63, 127,
)

OFFICIAL_MONTGOMERY_ZETAS_SIGNED = (
    -1044, -758, -359, -1517, 1493, 1422, 287, 202,
    -171, 622, 1577, 182, 962, -1202, -1474, 1468,
    573, -1325, 264, 383, -829, 1458, -1602, -130,
    -681, 1017, 732, 608, -1542, 411, -205, -1571,
    1223, 652, -552, 1015, -1293, 1491, -282, -1544,
    516, -8, -320, -666, -1618, -1162, 126, 1469,
    -853, -90, -271, 830, 107, -1421, -247, -951,
    -398, 961, -1508, -725, 448, -1065, 677, -1275,
    -1103, 430, 555, 843, -1251, 871, 1550, 105,
    422, 587, 177, -235, -291, -460, 1574, 1653,
    -246, 778, 1159, -147, -777, 1483, -602, 1119,
    -1590, 644, -872, 349, 418, 329, -156, -75,
    817, 1097, 603, 610, 1322, -1285, -1465, 384,
    -1215, -136, 1218, -1335, -874, 220, -1187, -1659,
    -1185, -1530, -1278, 794, -1510, -854, -870, 478,
    -108, -308, 996, 991, 958, -1460, 1522, 1628,
)


def derive_standard_twiddles() -> tuple[int, ...]:
    """Return canonical standard-domain zetas in official schedule order."""
    if len(BIT_REVERSED_TREE) != 128:
        raise AssertionError("bit-reversed tree must contain 128 entries")
    if sorted(BIT_REVERSED_TREE) != list(range(128)):
        raise AssertionError("bit-reversed tree must be a permutation of 0..127")
    if len(OFFICIAL_MONTGOMERY_ZETAS_SIGNED) != 128:
        raise AssertionError("official zeta table must contain 128 entries")

    r_inverse = pow(MONTGOMERY_R, -1, Q)
    standard: list[int] = []

    for index, exponent in enumerate(BIT_REVERSED_TREE):
        expected_standard = pow(ROOT_OF_UNITY, exponent, Q)
        official_montgomery = OFFICIAL_MONTGOMERY_ZETAS_SIGNED[index] % Q
        expected_montgomery = (expected_standard * MONTGOMERY_R) % Q

        if official_montgomery != expected_montgomery:
            raise AssertionError(
                "official Montgomery zeta mismatch at "
                f"index={index}: got={official_montgomery}, "
                f"expected={expected_montgomery}"
            )

        converted = (official_montgomery * r_inverse) % Q
        if converted != expected_standard:
            raise AssertionError(
                "standard-domain conversion mismatch at "
                f"index={index}: got={converted}, expected={expected_standard}"
            )
        if not 0 <= converted < Q:
            raise AssertionError(f"non-canonical twiddle at index={index}")

        standard.append(converted)

    if standard[0] != 1:
        raise AssertionError("address 0 must contain the neutral twiddle 1")

    return tuple(standard)


def render_hex(values: tuple[int, ...]) -> str:
    return "".join(f"{value:04x}\n" for value in values)


def render_systemverilog(values: tuple[int, ...]) -> str:
    case_lines = "\n".join(
        f"            7'd{index}: twiddle_lookup = 16'd{value};"
        for index, value in enumerate(values)
    )

    return f"""// Generated by software/reference/generate_twiddles_3329.py.
// Do not edit this file manually.
//
// Twiddles are canonical standard-domain values in [0, 3328].
// The official reference's signed Montgomery-domain zetas are converted
// because this repository currently uses standard modular multiplication.

module twiddle_rom_3329 (
    input  logic        clk_i,
    input  logic        rst_ni,
    input  logic        valid_i,
    input  logic [6:0]  addr_i,
    output logic        valid_o,
    output logic [15:0] zeta_o
);
    logic       valid_s1;
    logic [6:0] addr_s1;

    function automatic logic [15:0] twiddle_lookup(
        input logic [6:0] addr
    );
        begin
            case (addr)
{case_lines}
                default: twiddle_lookup = 16'd0;
            endcase
        end
    endfunction

    always_ff @(posedge clk_i) begin
        if (!rst_ni) begin
            valid_s1 <= 1'b0;
            valid_o  <= 1'b0;
            addr_s1  <= '0;
            zeta_o   <= '0;
        end else begin
            valid_s1 <= valid_i;
            valid_o  <= valid_s1;

            if (valid_i)
                addr_s1 <= addr_i;

            if (valid_s1)
                zeta_o <= twiddle_lookup(addr_s1);
        end
    end
endmodule
"""


def write_or_check(path: Path, expected: str, check_only: bool) -> bool:
    """Write a generated file or verify that its committed contents match."""
    if check_only:
        if not path.exists():
            print(f"ERROR: missing generated file: {path}", file=sys.stderr)
            return False

        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            print(
                f"ERROR: generated file is stale: {path}\n"
                "Run: python3 software/reference/generate_twiddles_3329.py --write",
                file=sys.stderr,
            )
            return False
        return True

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    print(f"WROTE: {path}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="regenerate committed files")
    mode.add_argument("--check", action="store_true", help="verify committed files")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[2]
    values = derive_standard_twiddles()

    targets = (
        (
            repo_root / "rtl/ntt/twiddle_rom_3329.sv",
            render_systemverilog(values),
        ),
        (
            repo_root / "tb/vectors/twiddle_3329_standard.hex",
            render_hex(values),
        ),
    )

    ok = all(
        write_or_check(path, expected, args.check)
        for path, expected in targets
    )
    if not ok:
        return 1

    action = "verified" if args.check else "generated"
    print(
        f"PASS: {action} 128 q=3329 standard-domain twiddles; "
        "forward schedule uses addresses 1..127, inverse uses 127..1"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
