// Generated by software/reference/generate_twiddles_3329.py.
// Do not edit this file manually.
//
// Twiddles are canonical standard-domain values in [0, 3328].
// The official reference's signed Montgomery-domain zetas are converted
// because this repository currently uses standard modular multiplication.

module twiddle_rom_3329 (
    input  logic        clk_i,
    input  logic        rst_ni,
    input  logic        valid_i,
    input  logic [6:0]  addr_i,
    output logic        valid_o,
    output logic [15:0] zeta_o
);
    logic       valid_s1;
    logic [6:0] addr_s1;

    function automatic logic [15:0] twiddle_lookup(
        input logic [6:0] addr
    );
        begin
            case (addr)
            7'd0: twiddle_lookup = 16'd1;
            7'd1: twiddle_lookup = 16'd1729;
            7'd2: twiddle_lookup = 16'd2580;
            7'd3: twiddle_lookup = 16'd3289;
            7'd4: twiddle_lookup = 16'd2642;
            7'd5: twiddle_lookup = 16'd630;
            7'd6: twiddle_lookup = 16'd1897;
            7'd7: twiddle_lookup = 16'd848;
            7'd8: twiddle_lookup = 16'd1062;
            7'd9: twiddle_lookup = 16'd1919;
            7'd10: twiddle_lookup = 16'd193;
            7'd11: twiddle_lookup = 16'd797;
            7'd12: twiddle_lookup = 16'd2786;
            7'd13: twiddle_lookup = 16'd3260;
            7'd14: twiddle_lookup = 16'd569;
            7'd15: twiddle_lookup = 16'd1746;
            7'd16: twiddle_lookup = 16'd296;
            7'd17: twiddle_lookup = 16'd2447;
            7'd18: twiddle_lookup = 16'd1339;
            7'd19: twiddle_lookup = 16'd1476;
            7'd20: twiddle_lookup = 16'd3046;
            7'd21: twiddle_lookup = 16'd56;
            7'd22: twiddle_lookup = 16'd2240;
            7'd23: twiddle_lookup = 16'd1333;
            7'd24: twiddle_lookup = 16'd1426;
            7'd25: twiddle_lookup = 16'd2094;
            7'd26: twiddle_lookup = 16'd535;
            7'd27: twiddle_lookup = 16'd2882;
            7'd28: twiddle_lookup = 16'd2393;
            7'd29: twiddle_lookup = 16'd2879;
            7'd30: twiddle_lookup = 16'd1974;
            7'd31: twiddle_lookup = 16'd821;
            7'd32: twiddle_lookup = 16'd289;
            7'd33: twiddle_lookup = 16'd331;
            7'd34: twiddle_lookup = 16'd3253;
            7'd35: twiddle_lookup = 16'd1756;
            7'd36: twiddle_lookup = 16'd1197;
            7'd37: twiddle_lookup = 16'd2304;
            7'd38: twiddle_lookup = 16'd2277;
            7'd39: twiddle_lookup = 16'd2055;
            7'd40: twiddle_lookup = 16'd650;
            7'd41: twiddle_lookup = 16'd1977;
            7'd42: twiddle_lookup = 16'd2513;
            7'd43: twiddle_lookup = 16'd632;
            7'd44: twiddle_lookup = 16'd2865;
            7'd45: twiddle_lookup = 16'd33;
            7'd46: twiddle_lookup = 16'd1320;
            7'd47: twiddle_lookup = 16'd1915;
            7'd48: twiddle_lookup = 16'd2319;
            7'd49: twiddle_lookup = 16'd1435;
            7'd50: twiddle_lookup = 16'd807;
            7'd51: twiddle_lookup = 16'd452;
            7'd52: twiddle_lookup = 16'd1438;
            7'd53: twiddle_lookup = 16'd2868;
            7'd54: twiddle_lookup = 16'd1534;
            7'd55: twiddle_lookup = 16'd2402;
            7'd56: twiddle_lookup = 16'd2647;
            7'd57: twiddle_lookup = 16'd2617;
            7'd58: twiddle_lookup = 16'd1481;
            7'd59: twiddle_lookup = 16'd648;
            7'd60: twiddle_lookup = 16'd2474;
            7'd61: twiddle_lookup = 16'd3110;
            7'd62: twiddle_lookup = 16'd1227;
            7'd63: twiddle_lookup = 16'd910;
            7'd64: twiddle_lookup = 16'd17;
            7'd65: twiddle_lookup = 16'd2761;
            7'd66: twiddle_lookup = 16'd583;
            7'd67: twiddle_lookup = 16'd2649;
            7'd68: twiddle_lookup = 16'd1637;
            7'd69: twiddle_lookup = 16'd723;
            7'd70: twiddle_lookup = 16'd2288;
            7'd71: twiddle_lookup = 16'd1100;
            7'd72: twiddle_lookup = 16'd1409;
            7'd73: twiddle_lookup = 16'd2662;
            7'd74: twiddle_lookup = 16'd3281;
            7'd75: twiddle_lookup = 16'd233;
            7'd76: twiddle_lookup = 16'd756;
            7'd77: twiddle_lookup = 16'd2156;
            7'd78: twiddle_lookup = 16'd3015;
            7'd79: twiddle_lookup = 16'd3050;
            7'd80: twiddle_lookup = 16'd1703;
            7'd81: twiddle_lookup = 16'd1651;
            7'd82: twiddle_lookup = 16'd2789;
            7'd83: twiddle_lookup = 16'd1789;
            7'd84: twiddle_lookup = 16'd1847;
            7'd85: twiddle_lookup = 16'd952;
            7'd86: twiddle_lookup = 16'd1461;
            7'd87: twiddle_lookup = 16'd2687;
            7'd88: twiddle_lookup = 16'd939;
            7'd89: twiddle_lookup = 16'd2308;
            7'd90: twiddle_lookup = 16'd2437;
            7'd91: twiddle_lookup = 16'd2388;
            7'd92: twiddle_lookup = 16'd733;
            7'd93: twiddle_lookup = 16'd2337;
            7'd94: twiddle_lookup = 16'd268;
            7'd95: twiddle_lookup = 16'd641;
            7'd96: twiddle_lookup = 16'd1584;
            7'd97: twiddle_lookup = 16'd2298;
            7'd98: twiddle_lookup = 16'd2037;
            7'd99: twiddle_lookup = 16'd3220;
            7'd100: twiddle_lookup = 16'd375;
            7'd101: twiddle_lookup = 16'd2549;
            7'd102: twiddle_lookup = 16'd2090;
            7'd103: twiddle_lookup = 16'd1645;
            7'd104: twiddle_lookup = 16'd1063;
            7'd105: twiddle_lookup = 16'd319;
            7'd106: twiddle_lookup = 16'd2773;
            7'd107: twiddle_lookup = 16'd757;
            7'd108: twiddle_lookup = 16'd2099;
            7'd109: twiddle_lookup = 16'd561;
            7'd110: twiddle_lookup = 16'd2466;
            7'd111: twiddle_lookup = 16'd2594;
            7'd112: twiddle_lookup = 16'd2804;
            7'd113: twiddle_lookup = 16'd1092;
            7'd114: twiddle_lookup = 16'd403;
            7'd115: twiddle_lookup = 16'd1026;
            7'd116: twiddle_lookup = 16'd1143;
            7'd117: twiddle_lookup = 16'd2150;
            7'd118: twiddle_lookup = 16'd2775;
            7'd119: twiddle_lookup = 16'd886;
            7'd120: twiddle_lookup = 16'd1722;
            7'd121: twiddle_lookup = 16'd1212;
            7'd122: twiddle_lookup = 16'd1874;
            7'd123: twiddle_lookup = 16'd1029;
            7'd124: twiddle_lookup = 16'd2110;
            7'd125: twiddle_lookup = 16'd2935;
            7'd126: twiddle_lookup = 16'd885;
            7'd127: twiddle_lookup = 16'd2154;
                default: twiddle_lookup = 16'd0;
            endcase
        end
    endfunction

    always_ff @(posedge clk_i) begin
        if (!rst_ni) begin
            valid_s1 <= 1'b0;
            valid_o  <= 1'b0;
            addr_s1  <= '0;
            zeta_o   <= '0;
        end else begin
            valid_s1 <= valid_i;
            valid_o  <= valid_s1;

            if (valid_i)
                addr_s1 <= addr_i;

            if (valid_s1)
                zeta_o <= twiddle_lookup(addr_s1);
        end
    end
endmodule
